-- Contenido inicial Knowledge Base (4 guías evergreen, ES/EN), pensado para SEO y GEO:
-- pregunta en el título, respuesta directa en el primer párrafo, estructura clara.
-- Ejecutar en Supabase → SQL Editor. Se publican directamente (is_published = true).
-- Revisa el texto antes de ejecutar: es TU voz y TU empresa quien lo firma.

insert into kb_articles (slug, category, title_es, title_en, summary_es, summary_en, body_es, body_en, is_published) values

('que-es-digital-signage-retail', 'guia',
 '¿Qué es el digital signage en retail y cómo se mide si funciona?',
 'What is digital signage in retail and how do you measure whether it works?',
 'Qué es la cartelería digital en tienda, para qué sirve en cada tramo del recorrido de compra y qué métricas permiten saber si está vendiendo.',
 'What in-store digital signage is, what it does at each stage of the shopper journey and which metrics tell you whether it is selling.',
 E'El digital signage (cartelería digital) es el uso de pantallas profesionales, gestionadas desde un CMS, para comunicar mensajes que se pueden cambiar, programar y personalizar según el momento, la tienda o el perfil del cliente.\n\n¿Para qué sirve en una tienda?\nEn el escaparate detiene al que pasa. En el interior acompaña la decisión de compra con categoría, precio y recomendación. En la trastienda informa y forma al equipo.\n\n¿Cuándo deja de funcionar?\nCuando se instala una vez, se carga un bucle y se olvida. El mismo contenido a cualquier hora, para cualquier perfil y sin relación con el stock real no aprovecha la inversión.\n\n¿Cómo se mide?\n1. Define antes el objetivo de negocio (tráfico a tienda, venta de una categoría, rotación de stock, comunicación interna).\n2. Elige la métrica que lo refleja en ese punto de venta: visitas, conversión, ventas de los productos mostrados, tiempo de espera o cumplimiento de campaña.\n3. Compara tiendas con y sin la acción, o periodos antes y después, y repite.\n\n¿Qué hace falta además de las pantallas?\nUn CMS que permita publicar en toda la red, instalación y mantenimiento con tiempos de respuesta comprometidos, y datos para decidir qué mostrar. En Altair Sense lo planteamos como un solo proyecto, de la estrategia a la operación.',
 E'Digital signage is the use of professional screens, managed from a CMS, to deliver messages that can be changed, scheduled and personalised by moment, store or customer profile.\n\nWhat is it for in a store?\nAt the shopfront it stops passers-by. Inside, it supports the purchase decision with category, price and recommendation. In the back of house, it informs and trains the team.\n\nWhen does it stop working?\nWhen it is installed once, a loop is loaded and it is forgotten. The same content at any hour, for any profile and unrelated to real stock does not make the most of the investment.\n\nHow do you measure it?\n1. Define the business goal first (store traffic, category sales, stock rotation, internal communication).\n2. Choose the metric that reflects it at that point of sale: visits, conversion, sales of the products shown, waiting time or campaign compliance.\n3. Compare stores with and without the action, or before-and-after periods, and repeat.\n\nWhat is needed besides screens?\nA CMS to publish across the whole network, installation and maintenance with committed response times, and data to decide what to show. At Altair Sense we approach it as a single project, from strategy to operations.',
 true),

('retail-media-tienda-fisica', 'guia',
 'Retail media en tienda física: qué es y cuándo tiene sentido',
 'In-store retail media: what it is and when it makes sense',
 'Qué es el retail media en punto de venta, qué necesita para funcionar y para qué tipo de retailers tiene más sentido.',
 'What in-store retail media is, what it needs to work and which kinds of retailers it suits best.',
 E'El retail media en tienda física consiste en usar los soportes del propio punto de venta (pantallas, lineales digitales, cartelería) para comunicar campañas de marcas, además de las del retailer, con medición de resultados.\n\n¿Cuándo tiene sentido?\nCuando el retailer distribuye varias marcas y tiene tráfico suficiente en tienda: supermercados, bricolaje, deporte, petcare, perfumería y cosmética son ejemplos habituales.\n\n¿Qué necesita para funcionar?\n1. Una red de pantallas bien ubicada y mantenida.\n2. Un CMS capaz de programar por tienda, franja y campaña.\n3. Una estrategia de contenidos por punto de contacto (escaparate, lineal, caja).\n4. Datos de venta y afluencia para demostrar el efecto de cada campaña.\n\n¿Sustituye a la retail tech?\nNo. Retail media es una solución propia, que se apoya en la infraestructura de retail tech y de digital signage de la tienda.\n\n¿Por dónde empezar?\nPor un piloto en pocas tiendas, con un objetivo y una métrica definidos antes de encender las pantallas.',
 E'In-store retail media means using the point of sale''s own touchpoints (screens, digital shelf displays, signage) to deliver brand campaigns, as well as the retailer''s own, with measured results.\n\nWhen does it make sense?\nWhen the retailer distributes several brands and has enough store traffic: supermarkets, DIY, sports, petcare, perfumery and cosmetics are common examples.\n\nWhat does it need to work?\n1. A well-placed, well-maintained screen network.\n2. A CMS able to schedule by store, time slot and campaign.\n3. A content strategy per touchpoint (shopfront, shelf, checkout).\n4. Sales and footfall data to prove the effect of each campaign.\n\nDoes it replace retail tech?\nNo. Retail media is a solution of its own, built on the store''s retail tech and digital signage infrastructure.\n\nWhere to start?\nWith a pilot in a few stores, with a goal and a metric defined before the screens are switched on.',
 true),

('mantenimiento-pantallas-digital-signage-sla', 'guia',
 'Mantenimiento de pantallas de digital signage: correctivo, preventivo, predictivo y SLA',
 'Digital signage maintenance: corrective, preventive, predictive and SLA',
 'Diferencias entre mantenimiento correctivo, preventivo y predictivo de pantallas, y cómo elegir un SLA según la criticidad de cada instalación.',
 'Differences between corrective, preventive and predictive screen maintenance, and how to choose an SLA by installation criticality.',
 E'Una pantalla apagada en tienda es una venta que no se comunica. Por eso el mantenimiento de digital signage se plantea por niveles.\n\nCorrectivo: se actúa cuando ya hay una incidencia. Requiere un canal sencillo para abrirla, un triaje claro y un plazo de respuesta comprometido.\n\nPreventivo: revisiones programadas para evitar fallos conocidos (limpieza, conectividad, actualizaciones, comprobación de contenido activo).\n\nPredictivo: detección temprana a partir de datos y del histórico de incidencias, para anticiparse a la avería.\n\n¿Qué es un SLA y cómo se elige?\nEl SLA es el tiempo de respuesta comprometido. Se fija por criticidad del sistema, no por tamaño del cliente: una sola pantalla puede ser crítica y una cadena entera puede no serlo. Los plazos habituales son 4 horas (crítico), 8 horas (en jornada), siguiente día laborable (NBD) y dos días laborables (2NBD).\n\n¿Cómo escala una incidencia?\nNivel 1 remoto (recepción, triaje y primera resolución), nivel 2 de análisis técnico con causa raíz documentada, y nivel 3 con escalada coordinada al fabricante. El cliente habla siempre con un único interlocutor.\n\nSiguiente paso recomendado: inventariar el parque instalado, revisar garantías vigentes y asignar criticidad por ubicación.',
 E'A switched-off screen in a store is a message that does not reach shoppers. That is why digital signage maintenance is approached in levels.\n\nCorrective: action once an incident exists. It needs a simple way to open it, clear triage and a committed response time.\n\nPreventive: scheduled checks to avoid known failures (cleaning, connectivity, updates, active-content verification).\n\nPredictive: early detection from data and incident history, to anticipate failure.\n\nWhat is an SLA and how do you choose one?\nThe SLA is the committed response time. It is set by system criticality, not client size: a single screen can be critical and a whole chain may not be. Typical times are 4 hours (critical), 8 hours (same day), next business day (NBD) and two business days (2NBD).\n\nHow does an incident escalate?\nLevel 1 remote (intake, triage and first resolution), level 2 technical analysis with documented root cause, and level 3 with coordinated escalation to the manufacturer. The client always talks to a single point of contact.\n\nRecommended next step: inventory the installed base, review current warranties and assign criticality by location.',
 true),

('connected-retail-strategy-crs', 'guia',
 'Connected Retail Strategy (CRS): la metodología detrás de Altair Sense y Lumen',
 'Connected Retail Strategy (CRS): the methodology behind Altair Sense and Lumen',
 'Qué es Connected Retail Strategy, por qué nació en 2025 y cómo se articula en Altair Sense y en la plataforma Lumen.',
 'What Connected Retail Strategy is, why it was born in 2025 and how it is articulated in Altair Sense and the Lumen platform.',
 E'Connected Retail Strategy (CRS) es una metodología creada por Roi Iglesias en marzo de 2025 ante el volumen de soluciones que gestiona el sector retail y que hoy pueden aunarse a través de una infraestructura de inteligencia artificial gestionada con criterio.\n\n¿Qué problema resuelve?\nUn retailer suele tener pantallas, CMS, sensores, ERP, etiquetas electrónicas y herramientas de datos que funcionan por separado. CRS propone conectarlos con un objetivo de negocio común.\n\n¿Cómo se aplica?\nCinco decisiones antes de tocar una pantalla: objetivos, tecnología, contenidos, métricas e IA aplicada. De ahí salen el proyecto y las métricas con las que se juzga.\n\n¿Qué relación tiene con Altair Sense y Lumen?\nDe CRS nació Altair Sense, que articula la metodología, con Lumen como plataforma y cerebro matriz al servicio del retail y otros entornos físicos. La plataforma es AI-ready y AI-agnostic: elegimos modelos y proveedores por proyecto, no por catálogo.',
 E'Connected Retail Strategy (CRS) is a methodology created by Roi Iglesias in March 2025 in response to the volume of solutions the retail sector manages, which can today be brought together through an AI infrastructure run with judgement.\n\nWhat problem does it solve?\nA retailer usually has screens, CMS, sensors, ERP, electronic shelf labels and data tools that work separately. CRS proposes connecting them around a shared business goal.\n\nHow is it applied?\nFive decisions before touching a screen: objectives, technology, content, metrics and applied AI. The project and the metrics it is judged by come from there.\n\nHow does it relate to Altair Sense and Lumen?\nAltair Sense was born from CRS and articulates the methodology, with Lumen as the platform and core brain serving retail and other physical environments. The platform is AI-ready and AI-agnostic: we choose models and providers per project, not from a catalogue.',
 true)
on conflict (slug) do nothing;
